profiles:
  active: dev

server:
  port: 9998

eureka:
  client:
    serviceUrl:
      defaultZone: http://172.20.0.122:8761/eureka/
  instance:
    prefer-ip-address: true

spring:
  datasource:
    ### useSSL=true 需要开启mysql端的ssl认证，后期需要再做
    url: jdbc:mysql://mha.db.msb.com:13306/msb_id_generator_dev?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
    schema:
    username: root
    password: mashibing
    driver-class-name: com.mysql.jdbc.Driver
    #连接池的配置信息
    initialSize: 50
    minIdle: 5
    maxActive: 100
    ## 配置获取连接等待超时的时间
    maxWait: 60000
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    #配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    #validationQuery: SELECT 1 FROM DUAL
    validationQueryTimeout: 10000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
    #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    # filters: stat,wall,log4j
# JWT config
jwt:
  # 请求头
  tokenHeader: X-Token
  secret: bx-generator
  # JWT的超期限时间(60*60*24*7)
  expiration: 604800
  # JWT负载中的头部
  tokenHead: 'Bearer '

bx:
  id-generator:
    snowflake:
      workerId: ''
      workerPort: ${server.port}
      generatorName: bx
      blockBackThreshold: 100
      etcdPoints: http://test.etcd.msb.com:2379
      keepAliveInterval: 1500
      leaseTTL: 3000
      systemReportInterval: 3000
      rootEtcdPath: /snowflake/bx
      pathForever: /snowflake/bx/forever
      pathTemp: /snowflake/bx/temp
      netInterfaceName: wlan0
    segment:
      nextSegmentFetchPercent: 0.9
      segmentFetchSize: 100
      threadLocalCacheEnabled: false
      threadLocalFetchSize: 10
