spring:
  profiles:
    active: ${profiles.active}
  application:
    name: id-generator-manager
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #连接池的配置信息
    initialSize: 50
    minIdle: 5
    maxActive: 100
    ## 配置获取连接等待超时的时间
    maxWait: 60000
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    #配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    #validationQuery: SELECT 1 FROM DUAL
    validationQueryTimeout: 10000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
    #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    # filters: stat,wall,log4j
# mybatis plus 设置
mybatis-plus:
  mapper-locations: classpath*:org/bx/idgenerator/manager/db/mapper/*Mapper.xml
  # 实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: org.bx.idgenerator.manager.entity
  # 主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
  global-config:
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #mybatis-plus.global-config.capital-mode=true
    #序列接口实现类配置
    #mybatis-plus.global-config.key-generator=com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# JWT config
jwt:
  # 请求头
  tokenHeader: X-Token
  secret: bx-generator
  # JWT的超期限时间(60*60*24*7)
  expiration: 604800
  # JWT负载中的头部
  tokenHead: 'Bearer '

management:
  endpoints:
    web:
      # 访问路径中没有actuator 直接是http://localhost:port/prometheus
      base-path: /
      exposure:
        include: 'prometheus'
  metrics:
    tags:
      application: ${spring.application.name}
logging:
  config: classpath:logback-config.xml
  level:
    root: INFO